### ISSUE TITLE
毕业论文和作者这篇方向差不多，请问可以提供代码吗。感谢感谢

### ISSUE THREAD

**Issue by Zhangfen21082** [xihongyang1999/GraphLearner#1]

**Comment by xihongyang1999** [comment]
好的好的，我最近有点忙，12月应该就可以了，感谢关注！

**Comment by Zhangfen21082** [comment]
非常感谢您，祝您论文多发，事业有成
&nbsp;


笑看今生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xihong ***@***.***&gt;; 
发送时间: 2024年11月25日(星期一) 下午5:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xihongyang1999/GraphLearner] 毕业论文和作者这篇方向差不多，请问可以提供代码吗。感谢感谢 (Issue #1)














 
好的好的，我最近有点忙，12月应该就可以了，感谢关注！

**Comment by Ysis0** [comment]
膜拜大佬，同求代码！希望可以大佬学习！

**Comment by xihongyang1999** [comment]
您好，代码已经公布，感谢关注，祝科研顺利。
